### ISSUE TITLE
After Template switch in new Page url is not generated again and url tree is missing

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu-standard#249] opened 2014-09-10 13:40 UTC
![switch-template](https://cloud.githubusercontent.com/assets/1698337/4218219/ae145bce-38ef-11e4-8e78-7e294479ec44.gif)

**Comment by danrot** [comment] 2015-03-18 08:13
Duplicate of https://github.com/sulu-cmf/sulu/issues/926

**Closed by danrot** 2015-03-18 08:13 UTC
Labels: Bug, duplicate
