### ISSUE TITLE
Internal Link Multiple Region are filled up with previous Blocks

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu-standard#345] opened 2014-10-24 08:36 UTC
I have the following blocks:

Block 1:
   - Block A
   - Block B
   - Block C

Block 2:
   - Block I
   - Block II

Block 3:
   - Block Z

In the twig Template i get
Block 1:
   - Block A
   - Block B
   - Block C

Block 2:
   - Block I
   - Block II
   - Block C

Block 3:
   - Block Z
   - Block II
   - Block C

All blocks are filled up with the previous.

**Comment by danrot** [comment] 2015-02-13 18:10
Duplicate of https://github.com/sulu-cmf/sulu-standard/issues/254

**Closed by danrot** 2015-02-13 18:10 UTC
Labels: Bug, duplicate
