### ISSUE TITLE
Smartcontent/Internal Links/Snippet add Filter for specific Template file

### ISSUE THREAD

**Issue by alexander-schranz** [sulu-cmf/sulu-standard#338] opened 2014-10-21 14:27 UTC
In the XML Template the Developer should able the set which templates should be shown.
Filter of one or multiple Templates.

**Comment by danrot** [comment] 2015-02-14 08:49
Duplicate of https://github.com/sulu-cmf/sulu/issues/427

**Closed by danrot** 2015-02-14 08:49 UTC
Labels: duplicate, Feature
